name: optimal_wrap_text
description: "A Flutter Text replacement that wraps short multi-line text over similarly sized lines for better visual balance."
version: 1.0.5
homepage: https://commingle.app
repository: https://github.com/chris-rutkowski/optimal_wrap_text

topics:
  - text
  - wrapping
  - user-interface
  - responsive

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
